-- =============================================================================
-- seed_a11y_testing_git_security_systemdesign: net-new questions covering
-- Accessibility, Testing, Git, Security, and System Design.
-- Idempotent (each insert is guarded by NOT EXISTS). source=core, approved.
--
-- Run in the Supabase SQL editor AFTER the schema migrations (001, 002) and the
-- other seed files. Independent of 004_dedupe.sql — these are brand-new
-- categories, so there is nothing here to de-duplicate against the core deck.
--
-- App wiring: these 5 categories were added to src/data/categories.js
-- (CAT_META + CAT_ORDER) and server/validate.js (CATEGORIES) so they show up in
-- the filter chips / stats / dropdowns and pass write-time validation.
-- =============================================================================

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','What is the accessibility tree, and how does it relate to the DOM?','The **accessibility tree** is a parallel structure the browser builds from the DOM specifically for assistive tech (screen readers, switch devices). Each node gets a computed **role**, **name**, and **state**, derived from HTML semantics, ARIA attributes, and CSS (elements hidden via `display:none` are pruned from it). It''s what a screen reader actually reads — not your raw HTML.','Does `visibility: hidden` remove a node from the accessibility tree the same way `display: none` does?','Yes — both remove the node entirely from the accessibility tree, same as from layout. `aria-hidden="true"` does too, but only for accessibility while the element stays visually present. `opacity: 0` does neither — the node stays in the tree and is still announced.','intermediate',ARRAY['accessibility-tree','aria','screen-readers','a11y']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='What is the accessibility tree, and how does it relate to the DOM?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','How do you trap focus inside a modal dialog for keyboard users?','On open, move focus to the modal (or its first focusable element), intercept `Tab`/`Shift+Tab` to cycle only through focusable elements **inside** the modal (wrapping at both ends), and set `aria-modal="true"` with `role="dialog"`. On close, return focus to the element that opened it — losing that return point is the most common bug.','Why is returning focus to the triggering element on close just as important as trapping it on open?','Without it, keyboard and screen-reader users land back at the top of the page (or wherever focus defaults to) with no sense of where they are, forcing them to re-navigate from scratch to continue their task.','advanced',ARRAY['focus-management','modal','keyboard-navigation','aria']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='How do you trap focus inside a modal dialog for keyboard users?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','What are ARIA live regions, and when do you use them?','`aria-live` marks a region so screen readers announce content changes **without the user needing to move focus there** — essential for toast notifications, form validation errors, or a loading status that appears dynamically. `aria-live="polite"` waits for a pause before announcing; `"assertive"` interrupts immediately.','Why should `aria-live="assertive"` be used sparingly?','It interrupts whatever the screen reader is currently announcing, which is jarring and can cause users to lose their place. Reserve it for urgent, time-sensitive messages like a failed payment; use `"polite"` for everything else.','advanced',ARRAY['aria-live','screen-readers','notifications','dynamic-content']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='What are ARIA live regions, and when do you use them?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','What contrast ratio does WCAG require for text, and how do you check it?','WCAG 2.1 **AA** requires a contrast ratio of at least **4.5:1** for normal text and **3:1** for large text (≥18pt, or ≥14pt bold) against its background. Check it with browser DevTools'' color picker (shows the ratio live), or tools like WebAIM''s contrast checker.','Does a higher contrast ratio requirement apply to UI components like button borders and icons?','Yes — WCAG 2.1 also introduced a **3:1** minimum for the visual boundaries of interactive UI components and meaningful graphics, separate from the text-contrast rule.','beginner',ARRAY['contrast','wcag','color','visual-accessibility']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='What contrast ratio does WCAG require for text, and how do you check it?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','What is a "skip to content" link, and why does every page need one?','A visually-hidden link, the very first focusable element on the page, that jumps keyboard users straight past repeated navigation (header, nav menu) to the main content — usually revealed on focus with `.sr-only:focus`. Without it, a keyboard user has to Tab through every nav link on every single page load.','How do you implement it so it''s invisible until focused, but not `display: none`?','Use a class that visually hides it off-screen (absolute positioning far left, or clip) rather than `display:none`/`visibility:hidden` — those would also remove it from the tab order. On `:focus`, reposition it back on-screen so sighted keyboard users can see where they landed.','intermediate',ARRAY['skip-link','keyboard-navigation','sr-only','navigation']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='What is a "skip to content" link, and why does every page need one?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','What are landmark roles (`main`, `nav`, `banner`, `contentinfo`), and why do they matter?','Landmarks mark the major regions of a page so screen reader users can jump directly between them (e.g. "skip to main content") instead of reading linearly top to bottom. Semantic HTML elements provide them for free: `<main>` → `main`, `<nav>` → `navigation`, `<header>` (top-level) → `banner`, `<footer>` (top-level) → `contentinfo`.','If you must use a `<div>` instead of a semantic element, how do you restore the landmark?','Add the matching `role` attribute explicitly, e.g. `<div role="navigation">` — it restores the landmark for assistive tech, but the native semantic element is always preferable since it comes with the role for free and needs no upkeep.','intermediate',ARRAY['landmarks','semantic-html','navigation','screen-readers']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='What are landmark roles (`main`, `nav`, `banner`, `contentinfo`), and why do they matter?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Accessibility','How do you make a custom dropdown/combobox component accessible?','Follow the ARIA **combobox pattern**: the input gets `role="combobox"`, `aria-expanded`, and `aria-controls` pointing at the listbox; the listbox gets `role="listbox"`; options get `role="option"` and `aria-selected`. Support full keyboard interaction (`↑`/`↓` to move, `Enter` to select, `Esc` to close) and announce the active option via `aria-activedescendant` rather than moving real DOM focus.','Why use `aria-activedescendant` instead of actually moving focus to each option as the user arrows through them?','Moving real focus away from the input would close the virtual keyboard on mobile and break typing. `aria-activedescendant` lets the input keep real focus while the screen reader is told which option is "virtually" active.','advanced',ARRAY['combobox','aria','keyboard-navigation','custom-components']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Accessibility' AND q='How do you make a custom dropdown/combobox component accessible?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','What is the testing pyramid, and why does the shape matter?','A model for how test-suite investment should be distributed: **many** fast, cheap **unit tests** at the base, **fewer integration tests** in the middle, and a **small number** of slow, expensive **E2E tests** at the top. Inverting it (an "ice cream cone" — mostly E2E) gives a slow, flaky suite that''s expensive to maintain.','Why are E2E tests the most expensive layer, beyond just runtime?','They spin up a real browser and often a real backend, so they''re slow, flaky (network timing, animations), and a single UI change can break many of them at once — high maintenance cost per test written.','intermediate',ARRAY['testing-pyramid','test-strategy','e2e','unit-tests']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='What is the testing pyramid, and why does the shape matter?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','What does React Testing Library mean by "test the behavior, not the implementation"?','Query and interact with components the way a **user** would — by visible text, label, or ARIA role (`getByRole(''button'', {name: ''Submit''})`) — rather than reaching into internal state, props, or CSS classes. This means refactoring a component''s internals (renaming a hook, restructuring markup) shouldn''t break its tests, as long as the user-facing behavior is unchanged.','Why does RTL deliberately make it awkward to select an element by class name or test id?','It''s a design choice: `getByTestId` exists but is de-prioritized in favor of role/label/text queries, because tests coupled to implementation details (classes, DOM structure) break on harmless refactors and give false confidence about what real users experience.','intermediate',ARRAY['react-testing-library','testing-philosophy','queries','user-centric']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='What does React Testing Library mean by "test the behavior, not the implementation"?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','What is snapshot testing, and what are its pitfalls?','A snapshot test renders a component, serializes the output, and compares it against a saved reference file on future runs — flagging any diff. It''s fast to write but easy to abuse: large snapshots become unreadable diffs that developers rubber-stamp with `--ci=false --updateSnapshot` without actually reviewing what changed, defeating the point.','When is a snapshot test actually a good fit?','For small, stable, structural output where any diff is meaningful and easy to eyeball — e.g. a design-system icon component''s rendered SVG. Avoid it for large component trees or anything that changes often for unrelated reasons.','intermediate',ARRAY['snapshot-testing','jest','test-maintenance','anti-patterns']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='What is snapshot testing, and what are its pitfalls?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','What''s the difference between `render`, `fireEvent`, and `userEvent` in React Testing Library?','`render` mounts the component into a virtual DOM for testing. `fireEvent` dispatches a **single, raw** DOM event (e.g. one `click`). `userEvent` simulates a **realistic sequence** of events a real user triggers — e.g. typing a character fires `keydown`, `keypress`, `input`, and `keyup` in order, which better catches bugs that depend on that full sequence.','Why is `userEvent.type()` generally preferred over `fireEvent.change()` for filling in a text input?','`fireEvent.change` jumps straight to the final value in one event, skipping the intermediate keystrokes. If a component has per-keystroke logic (debounced search, character limits, live validation), only `userEvent.type` actually exercises it.','intermediate',ARRAY['react-testing-library','user-event','fire-event','dom-events']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='What''s the difference between `render`, `fireEvent`, and `userEvent` in React Testing Library?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','How do you test a custom React hook?','Use `renderHook` (from `@testing-library/react`), which mounts the hook inside a minimal invisible test component and returns a `result` object exposing whatever the hook returns. Wrap state-updating calls (like a returned setter) in `act()` so React flushes updates before you assert, and use `rerender` to test how the hook responds to changed props.','Why do you need to wrap hook state updates in `act()` inside a test, when you never write `act()` in application code?','`act()` tells React to flush all pending state updates and effects synchronously before your assertions run, mimicking how the browser batches updates in production. Without it, you might assert against stale state because React hasn''t finished re-rendering yet.','advanced',ARRAY['custom-hooks','react-testing-library','render-hook','act']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='How do you test a custom React hook?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','What is Mock Service Worker (MSW), and why prefer it over mocking `fetch` directly?','MSW intercepts requests at the **network level** (via a Service Worker in the browser, or request interception in Node) and returns mocked responses — so your app code calls `fetch`/`axios` completely unmodified, unaware it''s being tested. Mocking `fetch` directly means replacing a global, which is brittle and can leak between tests or diverge from real request/response shape.','Why does testing at the network layer, rather than mocking the fetch client, give you more confidence?','Your component''s actual data-fetching code runs unmodified — the same code path exercised in production — so you''re testing real integration behavior (loading states, error handling, response parsing) instead of a hand-wired stub that could drift from reality.','advanced',ARRAY['msw','mocking','api-testing','integration-tests']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='What is Mock Service Worker (MSW), and why prefer it over mocking `fetch` directly?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Testing','What makes a test "flaky", and how do you fix one?','A flaky test passes and fails **intermittently** with no code change — usually from unhandled async timing (asserting before a promise resolves), shared/leaked state between tests, real network or `Date.now()` calls, or relying on animation/CSS transition timing. Fix it by awaiting the right async utility (`findBy*`, `waitFor`), isolating state per test, and mocking timers/network instead of relying on real ones.','Why is `waitFor` generally safer than an arbitrary `setTimeout` delay in a test?','`waitFor` polls a condition and resolves as soon as it''s true (or times out), so it''s as fast as the app allows and doesn''t hard-code a guess about timing. A fixed `setTimeout` is either too short (still flaky) or wastefully slow, and both hide the real reason the state changes.','intermediate',ARRAY['flaky-tests','async-testing','wait-for','test-reliability']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Testing' AND q='What makes a test "flaky", and how do you fix one?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','`git merge` vs `git rebase` — what''s the difference?','**Merge** combines branches by creating a new merge commit with two parents, preserving full history exactly as it happened (including all the messy intermediate commits). **Rebase** replays your branch''s commits one by one onto the tip of the target branch, producing a **linear** history — but it rewrites commit hashes, which is dangerous on shared/pushed branches.','Why is `git rebase` considered unsafe on a branch other people are already pulling from?','Rebase rewrites commit hashes, so anyone who already pulled the old commits now has a diverging history from the rewritten one. Their next pull creates confusing duplicate commits or conflicts. Rule of thumb: only rebase local/unpushed work, or branches you''re certain no one else is using.','intermediate',ARRAY['git','rebase','merge','version-control']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='`git merge` vs `git rebase` — what''s the difference?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','`git reset` vs `git revert` — when do you use each?','**`git reset`** moves the branch pointer backward, optionally discarding commits and/or working-directory changes — it **rewrites history**, so use it only on local/unpushed commits. **`git revert`** creates a **new commit** that undoes a previous one''s changes, leaving history intact — safe to use on shared branches since nothing already-pushed is rewritten.','You need to undo a commit that''s already been pushed and pulled by teammates. Which one do you use, and why?','`git revert` — it adds a new commit undoing the change rather than rewriting history, so everyone''s existing commits and pulls stay valid. `git reset` on a shared branch would force everyone else into a broken, diverging history.','intermediate',ARRAY['git','reset','revert','undo-changes']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='`git reset` vs `git revert` — when do you use each?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','What is a detached HEAD state, and how do you get out of it?','Normally `HEAD` points to a branch, which points to a commit. Checking out a specific commit hash (or a tag) directly points `HEAD` **straight at that commit**, bypassing any branch — any new commits you make there aren''t attached to a branch and can be lost once you check out something else. Get out safely with `git switch -c new-branch-name` to save the work on a real branch, or `git switch main` (or any branch) to just abandon it.','If you made commits while in detached HEAD and then check out `main` without creating a branch first, what happens to those commits?','They become unreachable from any branch — not deleted immediately, but orphaned and eligible for Git''s garbage collection. They''re usually still recoverable for a while via `git reflog`, but the safe move is always to branch off before switching away.','intermediate',ARRAY['git','detached-head','head','branches']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='What is a detached HEAD state, and how do you get out of it?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','What does `git cherry-pick` do?','Applies the changes from a **specific commit** on another branch onto your current branch, creating a new commit with the same changes (and a new hash). Useful for pulling a single bug fix or feature into a branch without merging or rebasing the entire source branch.','What''s the classic use case for cherry-picking a hotfix?','A critical bug fix lands on `main`, and you need it on a `release` branch immediately without pulling in all of `main`''s other unreleased commits — cherry-pick just that one fix commit onto `release`.','intermediate',ARRAY['git','cherry-pick','hotfix','commits']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='What does `git cherry-pick` do?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','`git fetch` vs `git pull` — what''s the difference?','**`git fetch`** downloads new commits/branches from the remote into your local repo''s remote-tracking branches (e.g. `origin/main`), but doesn''t touch your working branch — safe, non-destructive, lets you review before merging. **`git pull`** is `git fetch` followed immediately by a `merge` (or `rebase`, with `--rebase`) into your current branch.','Why might a careful developer prefer `git fetch` + manual `git merge` over `git pull` on an important branch?','It lets you inspect incoming changes (`git log origin/main`, `git diff`) before merging them into your working branch, rather than having `pull` auto-merge immediately and potentially surface conflicts or surprises mid-work.','beginner',ARRAY['git','fetch','pull','remote']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='`git fetch` vs `git pull` — what''s the difference?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','What is `git stash` for?','Temporarily shelves uncommitted changes (staged and unstaged) so you get a clean working directory — e.g. to switch branches quickly to handle an urgent fix — without committing half-finished work. Restore them later with `git stash pop` (applies and removes from the stash list) or `git stash apply` (applies but keeps it stashed).','What''s the difference between `git stash pop` and `git stash apply`?','`pop` applies the stashed changes to your working directory **and** removes that entry from the stash list. `apply` does the same but **keeps** the entry in the stash — useful if you want to apply the same stash to multiple branches.','beginner',ARRAY['git','stash','workflow','uncommitted-changes']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='What is `git stash` for?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Git','What''s the difference between Git Flow and trunk-based development?','**Git Flow** uses long-lived branches (`develop`, `feature/*`, `release/*`, `hotfix/*`) with formal merge points — structured, but merges can be large and infrequent. **Trunk-based development** has everyone commit small, frequent changes directly to (or via very short-lived branches off) a single `main`/`trunk`, often behind feature flags, favoring continuous integration over long-lived branches.','Why do most teams practicing continuous deployment favor trunk-based development over Git Flow?','Long-lived feature branches drift further from `main` the longer they live, making merges bigger and riskier. Trunk-based development keeps changes small and integrated constantly, which pairs naturally with CI/CD and reduces integration pain — feature flags handle hiding incomplete work instead of a branch.','intermediate',ARRAY['git','git-flow','trunk-based-development','branching-strategy']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Git' AND q='What''s the difference between Git Flow and trunk-based development?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What is CSRF, and how do you prevent it?','**Cross-Site Request Forgery** tricks a logged-in user''s browser into submitting an unwanted request to a site they''re authenticated on (e.g. a malicious page auto-submits a form to your bank''s "transfer funds" endpoint), exploiting the browser sending cookies automatically. Prevent it with a **CSRF token** — a unique, unguessable value the server issues and validates per-request — combined with `SameSite=Lax` or `Strict` cookies, which stops cookies from being sent on cross-site requests in the first place.','Why doesn''t `SameSite=Strict` alone fully solve CSRF for every app?','It blocks cookies on cross-site requests, but older browsers may not support it, and some legitimate cross-site flows (an external link into your logged-in app) can break under `Strict`. A CSRF token gives defense in depth independent of cookie/browser behavior.','advanced',ARRAY['csrf','security','cookies','same-site']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What is CSRF, and how do you prevent it?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What is Content Security Policy (CSP), and what does it protect against?','A `Content-Security-Policy` HTTP header (or meta tag) that whitelists which sources scripts, styles, images, and other resources are allowed to load from — e.g. `script-src ''self'' https://trusted-cdn.com`. It''s a strong defense-in-depth layer against **XSS**: even if an attacker injects a `<script>` tag, the browser refuses to execute it if it violates the policy.','Why does CSP discourage inline `<script>` tags and inline event handlers like `onclick="..."`?','A strict CSP (without `''unsafe-inline''`) blocks all inline scripts by default, because inline script is exactly what an XSS injection typically looks like — forcing scripts into external files (or nonce/hash-approved inline blocks) closes off that entire attack surface.','advanced',ARRAY['csp','xss','security-headers','http-headers']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What is Content Security Policy (CSP), and what does it protect against?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What''s the difference between authentication and authorization?','**Authentication** verifies *who you are* (logging in — username/password, OAuth, biometrics). **Authorization** determines *what you''re allowed to do* once identified (permissions, roles, access control). A logged-in user can be authenticated but not authorized to view another user''s admin dashboard.','Why is checking authorization only in the frontend UI (hiding a button) not actually secure?','Hiding a button just changes what''s rendered — the underlying API endpoint is still reachable directly (e.g. via devtools or a raw request) unless the **server** also enforces the permission check on every request. Frontend hiding is UX polish, not a security boundary.','beginner',ARRAY['authentication','authorization','access-control','security-fundamentals']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What''s the difference between authentication and authorization?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What is clickjacking, and how do you prevent it?','An attacker embeds your site in an invisible `<iframe>` layered under a decoy UI, tricking users into clicking something on your (real, invisible) site while believing they''re clicking the decoy — e.g. an invisible "delete account" or "authorize payment" button. Prevent it by sending `X-Frame-Options: DENY` (or `SAMEORIGIN`) and/or a CSP `frame-ancestors` directive, telling browsers to refuse to render your page inside a frame at all.','Why has `frame-ancestors` in CSP largely replaced `X-Frame-Options`?','`frame-ancestors` supports listing multiple allowed origins and is part of the more expressive, actively-maintained CSP spec, while `X-Frame-Options` is older and more limited (essentially just deny/same-origin/one-allowed-origin). Sites often send both for broader browser compatibility.','advanced',ARRAY['clickjacking','security','x-frame-options','csp']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What is clickjacking, and how do you prevent it?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What does the cookie `SameSite` attribute do, and what are its three values?','It controls whether a cookie is sent on **cross-site** requests. `Strict`: never sent cross-site, even when following a link into your app. `Lax` (the modern default): sent on top-level navigations (clicking a link) but not on cross-site subrequests like images or form POSTs from another site — a reasonable balance for most session cookies. `None`: always sent cross-site, but requires `Secure` (HTTPS-only) — needed for legitimate third-party/embedded use cases.','Why would an embedded payment widget (loaded in an iframe on a merchant''s site) need `SameSite=None` on its cookie?','The cookie is being sent from a context where the top-level page is a different origin than the widget itself — that''s inherently a cross-site request, so anything stricter than `None` would block the cookie entirely and break the widget''s session.','advanced',ARRAY['cookies','samesite','security','csrf']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What does the cookie `SameSite` attribute do, and what are its three values?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What is a supply-chain attack, and how do lockfiles and `npm audit` help mitigate it?','A supply-chain attack compromises your app indirectly by injecting malicious code into a **dependency** you trust (or one of its own dependencies), rather than attacking your code directly — e.g. a popular npm package gets hijacked and a malicious version is published. A **lockfile** (`package-lock.json`, `yarn.lock`) pins exact dependency versions so an unreviewed update can''t silently slip in on a fresh install; `npm audit` (or Snyk/Dependabot) scans installed dependencies against known-vulnerability databases.','Why doesn''t a lockfile alone fully protect you if a maintainer''s account gets compromised and they publish a new malicious version under an existing version range?','A lockfile pins the version you already resolved — it protects against *future* installs silently picking up a new bad version. But if you re-run an update (`npm update`) or the compromised version matches a range you haven''t locked yet, the lockfile doesn''t stop it; you also need vulnerability scanning and careful review of dependency updates.','advanced',ARRAY['supply-chain','npm','lockfile','dependency-security']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What is a supply-chain attack, and how do lockfiles and `npm audit` help mitigate it?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'Security','What''s the difference between the `Secure`, `HttpOnly`, and `SameSite` cookie flags?','**`Secure`**: the cookie is only sent over HTTPS, never plain HTTP. **`HttpOnly`**: JavaScript (`document.cookie`) can''t read or write the cookie at all — a key defense against XSS stealing session tokens. **`SameSite`**: controls whether the cookie is sent on cross-site requests, mitigating CSRF. A well-secured session cookie sets all three.','Why is `HttpOnly` specifically the defense against an XSS attack stealing a session cookie, rather than CSP or SameSite?','Even if an attacker manages to inject and run JavaScript via XSS, `HttpOnly` means that script simply cannot read `document.cookie` to exfiltrate the session token — the browser withholds it from JS entirely, regardless of what the malicious script tries.','advanced',ARRAY['cookies','httponly','secure-flag','session-security']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='Security' AND q='What''s the difference between the `Secure`, `HttpOnly`, and `SameSite` cookie flags?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','How would you architect a frontend for real-time collaborative editing, like Google Docs?','Represent the document as a data structure that merges concurrent edits without conflicts — typically a **CRDT** (Conflict-free Replicated Data Type) or **Operational Transform** — synced over a persistent connection (WebSocket). Each client applies local edits optimistically and immediately, then broadcasts and merges remote operations in the background; presence (cursors, selections) is a separate lightweight, high-frequency channel since it doesn''t need the same durability guarantees as document content.','Why is a CRDT generally easier to reason about than Operational Transform for a new project?','OT requires a carefully-proven transform function for every pair of concurrent operation types and typically a central server to sequence operations. CRDTs are designed so that merging any two states is mathematically guaranteed to converge regardless of order, which removes an entire class of transform-correctness bugs — at some cost in data-structure overhead.','advanced',ARRAY['system-design','real-time','crdt','websocket','collaboration']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='How would you architect a frontend for real-time collaborative editing, like Google Docs?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','How do you design a caching strategy for data that changes at very different rates within the same app?','Tier caching by **volatility**: rarely-changing data (user profile, config, feature flags) gets long `staleTime`/`Cache-Control max-age` and can be cached aggressively or even statically generated; frequently-changing data (live inventory, chat) uses short/no cache with real-time invalidation (WebSocket push, polling, or `staleTime: 0`). A single blanket cache policy either serves stale critical data or refetches static data needlessly.','If a background push (WebSocket) tells the client a piece of "rarely-changing" cached data just changed, how should the client react?','Treat the push as a targeted invalidation signal — mark that specific cache entry stale and refetch it (or apply the pushed delta directly), rather than lowering the general staleTime for that data type going forward. The data is still rarely-changing on average; this is just an exception.','advanced',ARRAY['system-design','caching','staleTime','invalidation']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='How do you design a caching strategy for data that changes at very different rates within the same app?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','How would you design an infinite-scroll feed that stays performant at scale?','Combine **pagination/cursor-based fetching** (fetch the next page as the user nears the bottom, via `IntersectionObserver` on a sentinel element) with **list virtualization** (react-window) so only visible rows mount — otherwise thousands of loaded items all stay in the DOM and every scroll frame gets slower. Cap total retained items with a sliding window (unmount far-above content) if the feed can grow unbounded.','Why is `IntersectionObserver` preferred over a `scroll` event listener for triggering the next page fetch?','`scroll` fires extremely frequently and forces synchronous layout reads if you check element positions manually, so it needs throttling/debouncing to avoid jank. `IntersectionObserver` is asynchronous and browser-optimized — it notifies you only when the sentinel actually crosses the viewport, with no manual position math or throttling needed.','advanced',ARRAY['system-design','infinite-scroll','virtualization','intersection-observer']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='How would you design an infinite-scroll feed that stays performant at scale?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','How would you architect a multi-tenant frontend that supports per-client theming and branding?','Keep components themable purely through **CSS custom properties** (colors, spacing, radii, fonts) rather than hard-coded values, and resolve the tenant''s theme config (from a subdomain, path, or auth token) at app boot, injecting the resulting variables onto the root before first paint to avoid a flash of default styling. Tenant-specific assets (logo, favicon) and feature availability are driven by the same resolved config object, not scattered conditionals.','Why resolve and inject the tenant''s theme *before* the first paint rather than after the app mounts?','Applying theme variables after mount causes a visible flash of the default/wrong theme followed by a re-render into the correct one (FOUC-like). Resolving tenant identity server-side or in a blocking bootstrap step lets you set the CSS variables before anything paints.','advanced',ARRAY['system-design','multi-tenant','theming','css-custom-properties']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='How would you architect a multi-tenant frontend that supports per-client theming and branding?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','What is a design token system, and how does it keep multiple products visually consistent?','Design tokens are the atomic, named values of a design system — colors, spacing, typography scale, radii, shadows — defined **once** in a platform-agnostic format (often JSON) and compiled into platform-specific outputs (CSS custom properties for web, a Swift/Kotlin file for native apps). Components reference tokens (`--color-brand-primary`) instead of hard-coded values, so a rebrand or theme change is a one-place edit that propagates everywhere the token is used, across every product consuming it.','Why compile tokens into CSS custom properties rather than hard-coding them at build time into a static stylesheet?','Custom properties are resolved at **runtime** in the browser, so you can support light/dark mode or per-tenant theming by just swapping the values on a root element — no rebuild required. Build-time hard-coded values would need a fresh compile per theme.','intermediate',ARRAY['system-design','design-tokens','design-systems','theming']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='What is a design token system, and how does it keep multiple products visually consistent?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','How would you design frontend error handling and observability (logging, monitoring, alerting)?','Layer it: **React error boundaries** catch render-time crashes and show a fallback instead of a blank white screen; a **global error handler** (`window.onerror`, unhandled promise rejections) catches everything else. Every caught error gets reported to a monitoring service (e.g. Sentry) with context — user id, route, recent actions/breadcrumbs — so a stack trace alone isn''t the only signal. Pair this with **performance monitoring** (Core Web Vitals, API latency) and alerting thresholds so regressions surface before users report them.','Why do error boundaries alone not catch every kind of frontend error?','Error boundaries only catch errors thrown during React''s **render** phase (and lifecycle/constructor). They don''t catch errors in event handlers, async code (promises, `setTimeout`), or errors during server-side rendering — those need `window.onerror`/`unhandledrejection` listeners or try/catch at the call site.','advanced',ARRAY['system-design','error-handling','observability','monitoring','error-boundaries']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='How would you design frontend error handling and observability (logging, monitoring, alerting)?');

INSERT INTO submissions (cat,q,a,fq,fa,difficulty,tags,status,source)
SELECT 'System Design','How would you design offline-first support for a web app?','A **service worker** intercepts network requests and serves cached responses when offline (cache-first for static assets, network-first with cache fallback for API data). Writes made offline queue locally (IndexedDB) and sync to the server once connectivity returns, with a conflict-resolution strategy for data that changed server-side in the meantime. Surface connectivity state in the UI so users know when they''re viewing stale/offline data versus live data.','Why is a network-first (not cache-first) strategy usually better for API data specifically, even in an offline-first app?','Cache-first would serve stale data even when the network is available and fresher data exists. Network-first tries the live network first and only falls back to cache on failure, so users see current data whenever possible and stale data only as a genuine fallback.','advanced',ARRAY['system-design','offline-first','service-worker','pwa','sync']::text[],'approved','core'
WHERE NOT EXISTS (SELECT 1 FROM submissions WHERE source='core' AND cat='System Design' AND q='How would you design offline-first support for a web app?');
