// One-time seed generator.
//
// Reads the original static decks (existingCards.js + newCards.js) and emits a
// SQL file that inserts every card into the Supabase `submissions` table as an
// approved, "core" question. Run once, then paste the output into the Supabase
// SQL editor:
//
//   node scripts/generate-seed.mjs
//   → writes supabase/seed_core_questions.sql
//
// After the seed has been run in Supabase, the static data files are no longer
// used by the app and have been removed — this script is kept only for the
// record of how the DB was first populated.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

const { existingCards } = await import("../src/data/existingCards.js");
const { newCards } = await import("../src/data/newCards.js");

const cards = [...existingCards, ...newCards];

// SQL single-quote escape.
const q = (v) => "'" + String(v ?? "").replace(/'/g, "''") + "'";

const values = cards
  .map((c) => {
    const cat = q(c.cat);
    const question = q(c.q);
    const answer = q(c.a);
    const fq = q(c.fq || "");
    const fa = q(c.fa || "");
    const difficulty = q(c.difficulty || "intermediate");
    return `  (${cat}, ${question}, ${answer}, ${fq}, ${fa}, ${difficulty}, 'approved', 'core')`;
  })
  .join(",\n");

const sql = `-- =============================================================================
-- Seed: core questions (${cards.length} cards migrated from the original static deck)
-- Generated by scripts/generate-seed.mjs — run ONCE in the Supabase SQL editor.
-- Safe to re-run only after TRUNCATE; otherwise it will create duplicates.
-- =============================================================================

INSERT INTO submissions (cat, q, a, fq, fa, difficulty, status, source) VALUES
${values};
`;

const outPath = join(__dirname, "..", "supabase", "seed_core_questions.sql");
writeFileSync(outPath, sql, "utf8");
console.log(`Wrote ${cards.length} cards → ${outPath}`);
