-- =============================================================================
-- 003_enrich_core: backfill tags + real difficulty on the 253 core questions.
-- Non-destructive. Matches each row by exact question text + category.
-- Safe to re-run (idempotent UPDATEs).
-- =============================================================================

UPDATE submissions SET difficulty='beginner', tags=ARRAY['doctype','rendering-mode','standards-mode','html5']::text[] WHERE source='core' AND cat='HTML' AND q='What does the `<!DOCTYPE html>` declaration do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['display','block-inline','box-model','layout']::text[] WHERE source='core' AND cat='HTML' AND q='Difference between block, inline, and inline-block elements?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['semantic-html','accessibility','seo']::text[] WHERE source='core' AND cat='HTML' AND q='What are semantic HTML elements and why use them?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['semantic-html','block-inline','div-span']::text[] WHERE source='core' AND cat='HTML' AND q='What''s the difference between `<div>` and `<span>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['alt-text','accessibility','images','seo']::text[] WHERE source='core' AND cat='HTML' AND q='Why is the `alt` attribute on images important?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['id-class','specificity','selectors']::text[] WHERE source='core' AND cat='HTML' AND q='What''s the difference between `id` and `class`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['data-attributes','dataset','custom-attributes']::text[] WHERE source='core' AND cat='HTML' AND q='What are `data-*` attributes?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['semantic-html','accessibility','text-formatting']::text[] WHERE source='core' AND cat='HTML' AND q='`<strong>`/`<b>` and `<em>`/`<i>` — what''s the difference?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['semantic-html','document-structure','accessibility']::text[] WHERE source='core' AND cat='HTML' AND q='Difference between `<section>`, `<article>`, and `<div>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['dom','browser','document']::text[] WHERE source='core' AND cat='HTML' AND q='What is the DOM?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['script-loading','async-defer','performance','html-parsing']::text[] WHERE source='core' AND cat='HTML' AND q='Difference between `<script>`, `<script async>`, and `<script defer>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['void-elements','html-syntax']::text[] WHERE source='core' AND cat='HTML' AND q='What are void (self-closing) elements?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['head','metadata','document-structure']::text[] WHERE source='core' AND cat='HTML' AND q='What goes in the `<head>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['viewport','meta-tags','responsive-design','mobile']::text[] WHERE source='core' AND cat='HTML' AND q='What does the viewport meta tag do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['forms','http-methods','get-post']::text[] WHERE source='core' AND cat='HTML' AND q='Difference between GET and POST in forms?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['input-types','forms','html5','validation']::text[] WHERE source='core' AND cat='HTML' AND q='Name some HTML5 input types and their value.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['web-storage','localstorage','sessionstorage','cookies']::text[] WHERE source='core' AND cat='HTML' AND q='localStorage vs sessionStorage vs cookies?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['accessibility','aria','assistive-technology']::text[] WHERE source='core' AND cat='HTML' AND q='What is web accessibility (a11y) and what is ARIA?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tabindex','focus-management','accessibility','keyboard-navigation']::text[] WHERE source='core' AND cat='HTML' AND q='What does the `tabindex` attribute do?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['forms','labels','accessibility']::text[] WHERE source='core' AND cat='HTML' AND q='What is the `<label>`''s `for` attribute?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['responsive-images','srcset','picture-element','performance']::text[] WHERE source='core' AND cat='HTML' AND q='What are responsive images with `srcset` / `<picture>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['lists','semantic-html']::text[] WHERE source='core' AND cat='HTML' AND q='Difference between `<ol>`, `<ul>`, and `<dl>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['meta-tags','seo','metadata']::text[] WHERE source='core' AND cat='HTML' AND q='What are meta tags used for?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['link-element','anchor','hyperlinks']::text[] WHERE source='core' AND cat='HTML' AND q='Difference between `<link>` and `<a>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['forms','fieldset','accessibility']::text[] WHERE source='core' AND cat='HTML' AND q='What are `<fieldset>` and `<legend>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['box-model','layout','css-fundamentals']::text[] WHERE source='core' AND cat='CSS' AND q='Explain the CSS box model.';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['box-sizing','box-model','layout']::text[] WHERE source='core' AND cat='CSS' AND q='`box-sizing: content-box` vs `border-box`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['box-model','margin','padding']::text[] WHERE source='core' AND cat='CSS' AND q='Difference between margin and padding?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['specificity','cascade','selectors']::text[] WHERE source='core' AND cat='CSS' AND q='What is specificity and how is it calculated?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['cascade','specificity','css-fundamentals']::text[] WHERE source='core' AND cat='CSS' AND q='What is the cascade?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['positioning','layout']::text[] WHERE source='core' AND cat='CSS' AND q='Explain `position`: static, relative, absolute, fixed, sticky.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['display','visibility','opacity','accessibility']::text[] WHERE source='core' AND cat='CSS' AND q='`display: none` vs `visibility: hidden` vs `opacity: 0`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['flexbox','layout','alignment']::text[] WHERE source='core' AND cat='CSS' AND q='What is Flexbox and what are the main/cross axes?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['grid','flexbox','layout']::text[] WHERE source='core' AND cat='CSS' AND q='What is CSS Grid and when do you use it over Flexbox?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['units','responsive-design','typography']::text[] WHERE source='core' AND cat='CSS' AND q='Explain px, em, rem, %, vh/vw.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['pseudo-classes','pseudo-elements','selectors']::text[] WHERE source='core' AND cat='CSS' AND q='Pseudo-classes vs pseudo-elements?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['z-index','stacking-context','positioning']::text[] WHERE source='core' AND cat='CSS' AND q='What is `z-index` and a stacking context?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['inheritance','cascade','css-fundamentals']::text[] WHERE source='core' AND cat='CSS' AND q='How does inheritance work in CSS?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['combinators','selectors']::text[] WHERE source='core' AND cat='CSS' AND q='What are CSS combinators?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['media-queries','responsive-design']::text[] WHERE source='core' AND cat='CSS' AND q='What is a media query? Mobile-first vs desktop-first?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['centering','flexbox','alignment']::text[] WHERE source='core' AND cat='CSS' AND q='How do you center a `<div>` horizontally and vertically?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['custom-properties','variables','theming']::text[] WHERE source='core' AND cat='CSS' AND q='What are CSS custom properties (variables)?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['transitions','animations']::text[] WHERE source='core' AND cat='CSS' AND q='`transition` vs `animation`?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['transform','performance','compositing']::text[] WHERE source='core' AND cat='CSS' AND q='Does `transform` affect layout?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['reflow','repaint','performance','rendering']::text[] WHERE source='core' AND cat='CSS' AND q='Reflow (layout) vs repaint?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['overflow','layout']::text[] WHERE source='core' AND cat='CSS' AND q='What are the values of `overflow`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['pseudo-classes','selectors','nth-child']::text[] WHERE source='core' AND cat='CSS' AND q='`:nth-child()` vs `:nth-of-type()`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['float','clear','layout']::text[] WHERE source='core' AND cat='CSS' AND q='What is `float` and `clear`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['bem','naming-conventions','css-architecture']::text[] WHERE source='core' AND cat='CSS' AND q='What is BEM?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['important','specificity','cascade']::text[] WHERE source='core' AND cat='CSS' AND q='When should you use `!important`, and why avoid it?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['sizing','responsive-design','layout']::text[] WHERE source='core' AND cat='CSS' AND q='Difference between `min-width`, `max-width`, and `width`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['css-fundamentals','stylesheets','best-practices']::text[] WHERE source='core' AND cat='CSS' AND q='Inline vs internal vs external CSS?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['variables','scope','hoisting','block-scope']::text[] WHERE source='core' AND cat='JavaScript' AND q='`var` vs `let` vs `const`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hoisting','scope','temporal-dead-zone','var']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is hoisting?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['equality','type-coercion','operators']::text[] WHERE source='core' AND cat='JavaScript' AND q='`==` vs `===`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['closures','scope','lexical-scope','functions']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is a closure?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['this','execution-context','binding','functions']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is the `this` keyword?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['arrow-functions','this','functions','es6']::text[] WHERE source='core' AND cat='JavaScript' AND q='Arrow functions vs regular functions?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['event-loop','asynchronous','microtasks','call-stack']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is the event loop?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['asynchronous','synchronous','concurrency']::text[] WHERE source='core' AND cat='JavaScript' AND q='Synchronous vs asynchronous?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['promises','asynchronous','promise-states']::text[] WHERE source='core' AND cat='JavaScript' AND q='What are Promises and their states?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['async-await','promises','asynchronous']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is `async`/`await`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['null','undefined','primitives']::text[] WHERE source='core' AND cat='JavaScript' AND q='`null` vs `undefined`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['truthy-falsy','type-coercion','booleans']::text[] WHERE source='core' AND cat='JavaScript' AND q='What are truthy and falsy values?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['array-methods','iteration','higher-order-functions','reduce']::text[] WHERE source='core' AND cat='JavaScript' AND q='`map` vs `filter` vs `reduce` vs `forEach`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['spread','rest','es6','operators']::text[] WHERE source='core' AND cat='JavaScript' AND q='Spread vs rest operator?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['destructuring','es6','arrays','objects']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is destructuring?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['call-apply-bind','this','binding','functions']::text[] WHERE source='core' AND cat='JavaScript' AND q='`call` vs `apply` vs `bind`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['prototypes','inheritance','prototype-chain','objects']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is prototypal inheritance?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['event-delegation','event-bubbling','event-propagation','dom-events']::text[] WHERE source='core' AND cat='JavaScript' AND q='Event bubbling, capturing, and delegation?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['functions','hoisting','function-expressions','function-declarations']::text[] WHERE source='core' AND cat='JavaScript' AND q='Function declaration vs function expression?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['callbacks','functions','higher-order-functions','asynchronous']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is a callback?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['shallow-copy','deep-copy','references','objects']::text[] WHERE source='core' AND cat='JavaScript' AND q='Shallow copy vs deep copy?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['template-literals','es6','strings']::text[] WHERE source='core' AND cat='JavaScript' AND q='What are template literals?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['array-methods','slice','splice','mutation']::text[] WHERE source='core' AND cat='JavaScript' AND q='`slice` vs `splice`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['primitives','reference-types','value-vs-reference','memory']::text[] WHERE source='core' AND cat='JavaScript' AND q='Primitive vs reference types?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['json','serialization','parsing']::text[] WHERE source='core' AND cat='JavaScript' AND q='`JSON.parse` and `JSON.stringify`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['debounce','throttle','performance','rate-limiting']::text[] WHERE source='core' AND cat='JavaScript' AND q='Debouncing vs throttling?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['settimeout','setinterval','timers','asynchronous']::text[] WHERE source='core' AND cat='JavaScript' AND q='`setTimeout` vs `setInterval`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['higher-order-functions','functions','functional-programming','composition']::text[] WHERE source='core' AND cat='JavaScript' AND q='What are higher-order functions?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['dom','innerhtml','xss','performance']::text[] WHERE source='core' AND cat='JavaScript' AND q='`innerHTML` vs `textContent` vs `innerText`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['short-circuit','logical-operators','operators']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is short-circuit evaluation?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['optional-chaining','nullish-coalescing','operators','es2020']::text[] WHERE source='core' AND cat='JavaScript' AND q='Nullish coalescing (`??`) and optional chaining (`?.`)?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['nan','number','type-checking','edge-cases']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is `NaN` and how do you check for it?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['dom-events','addeventlistener','event-handlers']::text[] WHERE source='core' AND cat='JavaScript' AND q='`addEventListener` vs `onclick`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['strict-mode','error-handling','scope']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is `"use strict"`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['pure-functions','functional-programming','side-effects','immutability']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is a pure function?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['array-methods','find','filter','iteration']::text[] WHERE source='core' AND cat='JavaScript' AND q='`find` vs `filter`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['typeof','type-checking','operators','primitives']::text[] WHERE source='core' AND cat='JavaScript' AND q='What does `typeof` return?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['dom','dom-selection','queryselector']::text[] WHERE source='core' AND cat='JavaScript' AND q='How do you select DOM elements?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['immutability','functional-programming','references','react']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is immutability and why does it matter?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['loops','iteration','for-of','for-in']::text[] WHERE source='core' AND cat='JavaScript' AND q='`for...of` vs `for...in`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','utility-first','css-framework']::text[] WHERE source='core' AND cat='Tailwind' AND q='What is Tailwind CSS and what does "utility-first" mean?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','utility-first','tradeoffs']::text[] WHERE source='core' AND cat='Tailwind' AND q='Pros and cons of utility-first CSS?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','responsive-design','breakpoints','mobile-first']::text[] WHERE source='core' AND cat='Tailwind' AND q='How does Tailwind handle responsive design?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','breakpoints','responsive-design']::text[] WHERE source='core' AND cat='Tailwind' AND q='What are the default breakpoints?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','variants','pseudo-classes']::text[] WHERE source='core' AND cat='Tailwind' AND q='How do you apply hover, focus, and other states?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','bootstrap','css-framework','utility-first']::text[] WHERE source='core' AND cat='Tailwind' AND q='Tailwind vs Bootstrap — the core difference?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','configuration','theming']::text[] WHERE source='core' AND cat='Tailwind' AND q='How do you customize Tailwind''s theme?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','apply-directive','css-directives']::text[] WHERE source='core' AND cat='Tailwind' AND q='What is `@apply` and when should you use it?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','purging','jit','bundle-size']::text[] WHERE source='core' AND cat='Tailwind' AND q='How does Tailwind keep the production file small?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','dark-mode','theming','variants']::text[] WHERE source='core' AND cat='Tailwind' AND q='How do you implement dark mode?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','arbitrary-values','syntax']::text[] WHERE source='core' AND cat='Tailwind' AND q='What are arbitrary values?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','configuration','theming']::text[] WHERE source='core' AND cat='Tailwind' AND q='`theme.extend` vs overriding `theme` directly (v3)?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','spacing','design-tokens']::text[] WHERE source='core' AND cat='Tailwind' AND q='What is the spacing scale?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','react','conditional-classes','clsx']::text[] WHERE source='core' AND cat='Tailwind' AND q='How do you handle conditional classes in React?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','spacing','utility-classes']::text[] WHERE source='core' AND cat='Tailwind' AND q='Difference between `p-4`, `px-4`, and `py-4`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','group-modifier','peer-modifier','variants']::text[] WHERE source='core' AND cat='Tailwind' AND q='What are `group` and `peer` modifiers?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','layer-directive','css-directives','css-cascade']::text[] WHERE source='core' AND cat='Tailwind' AND q='What does `@layer` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','utility-first','tradeoffs']::text[] WHERE source='core' AND cat='Tailwind' AND q='Utility classes vs hand-written CSS — the trade-off?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['react','components','virtual-dom','declarative']::text[] WHERE source='core' AND cat='React' AND q='What is React?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['virtual-dom','reconciliation','diffing','rendering']::text[] WHERE source='core' AND cat='React' AND q='What is the virtual DOM?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['jsx','syntax']::text[] WHERE source='core' AND cat='React' AND q='What is JSX?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['components','hooks','class-components','function-components']::text[] WHERE source='core' AND cat='React' AND q='Function components vs class components?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['props','state','components']::text[] WHERE source='core' AND cat='React' AND q='Props vs state?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['hooks','use-state','state']::text[] WHERE source='core' AND cat='React' AND q='What does `useState` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-effect','side-effects','lifecycle']::text[] WHERE source='core' AND cat='React' AND q='What does `useEffect` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['keys','lists','reconciliation','rendering']::text[] WHERE source='core' AND cat='React' AND q='Why do lists need a `key` prop?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['controlled-components','forms','refs','state']::text[] WHERE source='core' AND cat='React' AND q='Controlled vs uncontrolled components?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['state','lifting-state','props','component-design']::text[] WHERE source='core' AND cat='React' AND q='What is "lifting state up"?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['context','prop-drilling','state-management','hooks']::text[] WHERE source='core' AND cat='React' AND q='Prop drilling and the Context API?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-ref','dom','refs']::text[] WHERE source='core' AND cat='React' AND q='What does `useRef` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-memo','use-callback','memoization']::text[] WHERE source='core' AND cat='React' AND q='`useMemo` vs `useCallback`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['react-memo','memoization','performance','rendering']::text[] WHERE source='core' AND cat='React' AND q='What is `React.memo`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','custom-hooks','reusability']::text[] WHERE source='core' AND cat='React' AND q='What are custom hooks?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','rules-of-hooks']::text[] WHERE source='core' AND cat='React' AND q='What are the Rules of Hooks?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['fragments','jsx']::text[] WHERE source='core' AND cat='React' AND q='What is a Fragment?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['conditional-rendering','jsx','rendering']::text[] WHERE source='core' AND cat='React' AND q='How do you do conditional rendering?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['synthetic-events','events','event-delegation']::text[] WHERE source='core' AND cat='React' AND q='What are synthetic events?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['lazy-loading','suspense','code-splitting','performance']::text[] WHERE source='core' AND cat='React' AND q='What are lazy loading and Suspense?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-reducer','state-management']::text[] WHERE source='core' AND cat='React' AND q='What does `useReducer` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['state','immutability','reconciliation','rendering']::text[] WHERE source='core' AND cat='React' AND q='Why shouldn''t you mutate state directly?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-effect','cleanup','side-effects']::text[] WHERE source='core' AND cat='React' AND q='What is `useEffect` cleanup?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['hooks','use-layout-effect','use-effect','rendering','performance']::text[] WHERE source='core' AND cat='React' AND q='`useLayoutEffect` vs `useEffect`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['error-boundaries','error-handling','class-components']::text[] WHERE source='core' AND cat='React' AND q='What are error boundaries?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['reconciliation','virtual-dom','diffing','rendering']::text[] WHERE source='core' AND cat='React' AND q='What is reconciliation?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['strict-mode','development','debugging']::text[] WHERE source='core' AND cat='React' AND q='What is StrictMode?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['react-19','actions','hooks','concurrent-features']::text[] WHERE source='core' AND cat='React' AND q='What''s new in React 19?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['typescript','static-typing','tooling']::text[] WHERE source='core' AND cat='TypeScript' AND q='What is TypeScript and why use it?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['type-vs-interface','interface','type-alias','declaration-merging']::text[] WHERE source='core' AND cat='TypeScript' AND q='`type` vs `interface`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['any','unknown','never','top-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='`any` vs `unknown` vs `never`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['union-types','intersection-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='Union vs intersection types?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['generics','type-parameters']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are generics?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['enums','constants']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are enums?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['optional-properties','interfaces']::text[] WHERE source='core' AND cat='TypeScript' AND q='How do optional properties work?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['type-inference','type-annotations']::text[] WHERE source='core' AND cat='TypeScript' AND q='What is type inference?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['type-assertion','type-casting']::text[] WHERE source='core' AND cat='TypeScript' AND q='What is a type assertion (`as`)?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['literal-types','union-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are literal types?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tuples','arrays']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are tuples?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['readonly','immutability']::text[] WHERE source='core' AND cat='TypeScript' AND q='What does `readonly` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['utility-types','partial','pick','omit']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are utility types?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['keyof','typeof','type-operators']::text[] WHERE source='core' AND cat='TypeScript' AND q='What do `keyof` and `typeof` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['type-guards','narrowing','type-predicates']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are type guards / narrowing?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['discriminated-unions','narrowing','union-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are discriminated unions?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['function-types','function-signatures']::text[] WHERE source='core' AND cat='TypeScript' AND q='How do function types work?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['void','never','return-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='`void` vs `never`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['structural-typing','duck-typing','type-compatibility']::text[] WHERE source='core' AND cat='TypeScript' AND q='What is structural typing?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['non-null-assertion','null-safety']::text[] WHERE source='core' AND cat='TypeScript' AND q='What is the non-null assertion (`!`)?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['mapped-types','keyof','utility-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are mapped types?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['as-const','const-assertions','literal-types','readonly']::text[] WHERE source='core' AND cat='TypeScript' AND q='What does `as const` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['declaration-files','ambient-declarations','type-definitions']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are declaration files (`.d.ts`)?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tsconfig','strict-mode','compiler-options','strict-null-checks']::text[] WHERE source='core' AND cat='TypeScript' AND q='What does `strict` in tsconfig do?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['core-web-vitals','performance','metrics']::text[] WHERE source='core' AND cat='Performance' AND q='What are the Core Web Vitals?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['lcp','core-web-vitals','performance','metrics']::text[] WHERE source='core' AND cat='Performance' AND q='What is LCP and how do you improve it?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['inp','core-web-vitals','performance','metrics']::text[] WHERE source='core' AND cat='Performance' AND q='What is INP?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['cls','core-web-vitals','layout-shift','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is CLS and how do you avoid it?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['critical-rendering-path','rendering','dom','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is the critical rendering path?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['lazy-loading','performance','images','code-splitting']::text[] WHERE source='core' AND cat='Performance' AND q='What is lazy loading?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['code-splitting','bundling','lazy-loading','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is code splitting?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tree-shaking','bundling','es-modules','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is tree shaking?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['minification','compression','bundling','performance']::text[] WHERE source='core' AND cat='Performance' AND q='Minification vs compression?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['images','responsive-images','lazy-loading','performance']::text[] WHERE source='core' AND cat='Performance' AND q='How do you optimize images?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['caching','http-caching','cdn','performance']::text[] WHERE source='core' AND cat='Performance' AND q='How does caching improve performance?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['reflow','repaint','rendering','performance']::text[] WHERE source='core' AND cat='Performance' AND q='How do you reduce reflows and repaints?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['request-animation-frame','animations','rendering','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is `requestAnimationFrame`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['virtualization','rendering','react','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is list virtualization?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['resource-hints','preload','prefetch','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What are preload, prefetch, and preconnect?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['bundle-size','bundling','code-splitting','performance']::text[] WHERE source='core' AND cat='Performance' AND q='How do you reduce bundle size?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['web-workers','concurrency','threading','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What are web workers?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['render-blocking','critical-css','rendering','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What are render-blocking resources?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['app-router','pages-router','routing','data-fetching']::text[] WHERE source='core' AND cat='Next.js' AND q='What''s the difference between the App Router and the Pages Router?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['server-components','client-components','app-router','rsc']::text[] WHERE source='core' AND cat='Next.js' AND q='In the App Router, are components server or client by default?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['server-components','rsc','app-router','data-fetching']::text[] WHERE source='core' AND cat='Next.js' AND q='What is a React Server Component (RSC)?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['data-fetching','server-components','async-await','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='How do you fetch data in an App Router Server Component?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['ssr','ssg','isr','rendering']::text[] WHERE source='core' AND cat='Next.js' AND q='Explain SSR, SSG, and ISR in Next.js.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['data-fetching','getstaticprops','getserversideprops','pages-router']::text[] WHERE source='core' AND cat='Next.js' AND q='`getStaticProps` vs `getServerSideProps` (Pages Router)?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['next-link','routing','prefetching','navigation']::text[] WHERE source='core' AND cat='Next.js' AND q='What does `next/link` do that a plain `<a>` doesn''t?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['next-image','image-optimization','performance','lazy-loading']::text[] WHERE source='core' AND cat='Next.js' AND q='What is `next/image` and why use it?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['route-handlers','api-routes','app-router','http-methods']::text[] WHERE source='core' AND cat='Next.js' AND q='What are Route Handlers?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['middleware','edge-runtime','routing','authentication']::text[] WHERE source='core' AND cat='Next.js' AND q='What is Next.js Middleware?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['server-actions','mutations','forms','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='What are Server Actions?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['layouts','app-router','nested-layouts','routing']::text[] WHERE source='core' AND cat='Next.js' AND q='What''s the role of `layout.js`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['suspense','error-handling','loading-states','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='What do `loading.js` and `error.js` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['dynamic-routes','routing','catch-all-routes','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='How do dynamic routes work in the App Router?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['streaming','suspense','performance','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='What is streaming with Suspense in the App Router?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['metadata','seo','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='How does the Metadata API work?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['environment-variables','configuration','security']::text[] WHERE source='core' AND cat='Next.js' AND q='How do environment variables work in Next.js?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hydration','ssr','debugging']::text[] WHERE source='core' AND cat='Next.js' AND q='What causes a hydration error in Next.js?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['redirect','not-found','navigation','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='What''s the difference between `redirect()` and `notFound()`?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['parallel-routes','intercepting-routes','routing','app-router']::text[] WHERE source='core' AND cat='Next.js' AND q='What are parallel and intercepting routes?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['data-fetching','server-components','client-components','architecture']::text[] WHERE source='core' AND cat='Next.js' AND q='Where should data fetching live — Server or Client Components?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['caching','revalidation','data-fetching']::text[] WHERE source='core' AND cat='Next.js' AND q='Explain tag-based caching: `revalidateTag` / `revalidatePath`.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['data-fetching','swr','react-query','mutations']::text[] WHERE source='core' AND cat='Next.js' AND q='How do you do client-side data fetching/mutations in Next.js?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['use-router','routing','app-router','pages-router']::text[] WHERE source='core' AND cat='Next.js' AND q='How does `useRouter` differ between App and Pages routers?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-memo','use-callback','memoization','performance']::text[] WHERE source='core' AND cat='React' AND q='When should you use `useMemo` vs `useCallback`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['react-memo','memoization','performance','rendering']::text[] WHERE source='core' AND cat='React' AND q='What does `React.memo` do?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['hooks','use-layout-effect','use-effect','rendering','performance']::text[] WHERE source='core' AND cat='React' AND q='`useEffect` vs `useLayoutEffect`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-reducer','use-state','state-management']::text[] WHERE source='core' AND cat='React' AND q='What is `useReducer` and when beats `useState`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['controlled-components','forms','refs','state']::text[] WHERE source='core' AND cat='React' AND q='Controlled vs uncontrolled components?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['hooks','use-ref','dom','refs']::text[] WHERE source='core' AND cat='React' AND q='What is `useRef` for?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['portals','dom','modals','rendering']::text[] WHERE source='core' AND cat='React' AND q='What is a React Portal?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['error-boundaries','error-handling','class-components']::text[] WHERE source='core' AND cat='React' AND q='What is an Error Boundary?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['keys','lists','reconciliation','rendering']::text[] WHERE source='core' AND cat='React' AND q='Why does React need `key` props in lists?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['strict-mode','development','debugging']::text[] WHERE source='core' AND cat='React' AND q='What does StrictMode do in development?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['event-loop','microtasks','macrotasks','asynchronous','call-stack']::text[] WHERE source='core' AND cat='JavaScript' AND q='Explain the event loop: microtasks vs macrotasks.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['this','binding','execution-context','arrow-functions']::text[] WHERE source='core' AND cat='JavaScript' AND q='How does `this` binding work?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['deep-copy','shallow-copy','references','structured-clone']::text[] WHERE source='core' AND cat='JavaScript' AND q='Deep copy vs shallow copy?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['closures','scope','var','loops']::text[] WHERE source='core' AND cat='JavaScript' AND q='What is a closure, and a common gotcha?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['map','objects','data-structures','key-value']::text[] WHERE source='core' AND cat='JavaScript' AND q='`Map` vs plain object for key-value data?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['debounce','throttle','performance','rate-limiting']::text[] WHERE source='core' AND cat='JavaScript' AND q='Debounce vs throttle?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['equality','type-coercion','operators','comparison']::text[] WHERE source='core' AND cat='JavaScript' AND q='`==` vs `===`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['async-await','promises','asynchronous','error-handling']::text[] WHERE source='core' AND cat='JavaScript' AND q='What are `async`/`await` really doing?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['unknown','any','top-types','narrowing']::text[] WHERE source='core' AND cat='TypeScript' AND q='`unknown` vs `any`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['type-vs-interface','interface','type-alias','declaration-merging']::text[] WHERE source='core' AND cat='TypeScript' AND q='`type` vs `interface`?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['generics','type-parameters']::text[] WHERE source='core' AND cat='TypeScript' AND q='Explain generics with an example.';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['utility-types','partial','pick','omit','record']::text[] WHERE source='core' AND cat='TypeScript' AND q='What do `Partial`, `Pick`, `Omit`, and `Record` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['discriminated-unions','narrowing','union-types']::text[] WHERE source='core' AND cat='TypeScript' AND q='What is a discriminated union?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['enums','as-const','tree-shaking','const-assertions']::text[] WHERE source='core' AND cat='TypeScript' AND q='`enum` vs an `as const` object?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['satisfies','type-inference','type-widening']::text[] WHERE source='core' AND cat='TypeScript' AND q='What does the `satisfies` operator do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['keyof','typeof','type-operators']::text[] WHERE source='core' AND cat='TypeScript' AND q='What are `keyof` and `typeof` in a type context?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['specificity','cascade','selectors']::text[] WHERE source='core' AND cat='CSS' AND q='How does CSS specificity work?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['stacking-context','z-index','positioning']::text[] WHERE source='core' AND cat='CSS' AND q='What creates a stacking context, and why does `z-index` sometimes ''not work''?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['flexbox','grid','layout']::text[] WHERE source='core' AND cat='CSS' AND q='Flexbox vs Grid — when to use which?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['container-queries','media-queries','responsive-design']::text[] WHERE source='core' AND cat='CSS' AND q='What are container queries vs media queries?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['clamp','math-functions','responsive-design']::text[] WHERE source='core' AND cat='CSS' AND q='What do `min()`, `max()`, and `clamp()` do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['positioning','layout']::text[] WHERE source='core' AND cat='CSS' AND q='`relative` vs `absolute` vs `fixed` vs `sticky` positioning?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['forms','labels','accessibility']::text[] WHERE source='core' AND cat='HTML' AND q='Why associate a `<label>` with an input?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['script-loading','async-defer','performance','html-parsing']::text[] WHERE source='core' AND cat='HTML' AND q='`async` vs `defer` on a `<script>`?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['viewport','meta-tags','responsive-design','mobile']::text[] WHERE source='core' AND cat='HTML' AND q='What does the viewport meta tag do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['aria','accessibility','semantic-html']::text[] WHERE source='core' AND cat='HTML' AND q='What is ARIA, and what''s the first rule of ARIA?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['iframe','sandbox','security','embedding']::text[] WHERE source='core' AND cat='HTML' AND q='What does the `<iframe sandbox>` attribute do?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['critical-rendering-path','rendering','dom','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is the Critical Rendering Path?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['code-splitting','react','lazy-loading','suspense']::text[] WHERE source='core' AND cat='Performance' AND q='What is code splitting, and how in React?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['core-web-vitals','performance','metrics']::text[] WHERE source='core' AND cat='Performance' AND q='What are the Core Web Vitals?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tree-shaking','bundling','es-modules','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is tree shaking?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['caching','http-caching','cache-control','performance']::text[] WHERE source='core' AND cat='Performance' AND q='How does browser caching improve performance?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['lazy-loading','images','intersection-observer','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What is lazy loading, and how do you lazy-load images?';
UPDATE submissions SET difficulty='advanced', tags=ARRAY['memory-leaks','memory-management','spa','performance']::text[] WHERE source='core' AND cat='Performance' AND q='What causes memory leaks in a SPA, and how do you prevent them?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','utility-first','tradeoffs']::text[] WHERE source='core' AND cat='Tailwind' AND q='What''s the core idea — and tradeoff — of utility-first CSS?';
UPDATE submissions SET difficulty='beginner', tags=ARRAY['tailwind','responsive-design','breakpoints','mobile-first']::text[] WHERE source='core' AND cat='Tailwind' AND q='How do responsive styles work in Tailwind?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','dark-mode','theming','variants']::text[] WHERE source='core' AND cat='Tailwind' AND q='How does dark mode work in Tailwind?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','apply-directive','css-directives']::text[] WHERE source='core' AND cat='Tailwind' AND q='What does `@apply` do, and when should you avoid it?';
UPDATE submissions SET difficulty='intermediate', tags=ARRAY['tailwind','purging','jit','bundle-size']::text[] WHERE source='core' AND cat='Tailwind' AND q='How does Tailwind keep the CSS bundle small?';
